language: python
python:
- '3.5'
before_script:
  - sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv 9DA31620334BD75D9DCB49F368818C72E52529D4
  - echo "deb [ arch=amd64 ] https://repo.mongodb.org/apt/ubuntu trusty/mongodb-org/4.0 multiverse" | sudo tee /etc/apt/sources.list.d/mongodb-org-4.0.list
  - sudo apt-get update
  - sudo apt-get install -y mongodb-org=4.0.9 mongodb-org-server=4.0.9 mongodb-org-shell=4.0.9 mongodb-org-mongos=4.0.9 mongodb-org-tools=4.0.9
  - sudo rm /var/lib/mongodb/mongod.lock
  - sudo service mongod start
  - sleep 15
  - mongo --version
install: pip install -r requirements.txt
script: pytest
deploy:
  provider: pypi
  user: musyoka-morris
  password:
    secure: WXOxOu3Vfs4VfDZhMSXjq30aduj8kUTDQuCqqUi/n65kD+dgtL6zc9gsLlTMEUQCYjEchIjtb2ryfX1l8s5ii3fpu4WW7snlM9aUc9xCKYc7qtDBw5L8JfF8TFq+ujLOG26rBofDD59tzVOQgUJOJY66w1xLhfkmmXTd51GkHWfvdCBkO7sN/LZJTdL9d4RwSz/QmHDbeUMoFhofS4p8W6PJ1QvseBwbd/38OhmoFoB4POdLno0UXr9U9lz3Jnyv4G9pGuJCh31EQUY6NquqFvDKMChKufGnXhhhMAHXsVyumodzY1IwM8HyDc+ZzndS8/uHS5P280sdYdtwqGWWP/rr1dmmBye84QS3bzggmto7Gd7pXfpsBrksE/ng8Q53+SXGt0CpPsFVafOB0MfwULIAA5lqFZ1uTVR4eTyy+bXb7vgxXJ2sxVt0ftgNIQ68/lI0UwcKmsQEnV1rrF6UbSbwU8gRt+/8yohcaDyAnepSNUmsoXn5dHFWEbiwOUn540RuXPmCXrUQfeHuk0t5q8iiZexqoq+HSo7+7cyK7SCLb5vJlxfldcJ88a3hrxN7vYHuhmBwaIzTdKDIKryEH9Ks9hLIPHfmO//oQAQSzw2gSAt3F5D75NP1nksflZ8eSPEHj5pAIH9PKB9GlsFwd5Yjididdyr6P95Jop9M7Ak=
  distributions: sdist bdist_wheel
  skip_existing: true
